### ISSUE TITLE
Office 365 Emails Not Sending When Scripts Run

### ISSUE THREAD

**Issue by tcmp98724** [ZacksHomeLab/BitWarden#2]
Hello! Thank you for all your hard work and level of details in this project, you've done a fantastic job! I'm a newbie trying out Docker and various self-hosting projects, and followed your guide and got everything working, except, I'm having a heck of a time with getting the email portion to work. I am using Office 365, and the account is an actual user account, not a shared mailbox. The email works fine when it is coming from BitWarden itself, but it doesn't seem to work with the PS scripts on my Ubuntu Docker host. I've tried using the Send-MailMessage by itself and it works, so I know the service and my credential work. I feel like it's something not being passed through between the various PS functions, but I don't know enough to be able to tell for sure. And it's entirely possible it's something of my own doing, but I was hoping you might have some insight on it or suggestions to try. This is the error I keep getting...

Exception: Send-ZHLBWEmail: Failed sending email due to The SMTP server requires a secure connection or the client was not authenticated. The server response was: 5.7.57 Client not authenticated
to send mail.

Seems straightforward in the message, but as I said I know it works outside of it with Send-MailMessage if I just do a test message. In your guide in Chapter 4, "How-To Configure Email Notifications", all I did there was make sure my global.override.env file was correct, since everything else email-wise in BitWarden seems to work, I assumed that was all that was needed. Am I mistaken and I have to do one of the two options, regardless of if my email in BitWarden was working fine previously? Thanks for any input!

**Comment by ZacksHomeLab** [comment]
Hello! It could be an issue with SSL/TLS. Open the global environment file on your BitWarden server:
```
nano /opt/bitwarden/bwdata/env/global.override.env
```

Make sure you have the following settings (replace the username & password with your email account):
| Variables                            | Values                   |
|--------------------------------------|--------------------------|
| globalSettings__mail__smtp__host     | smtp.office365.com       |
| globalSettings__mail__smtp__port     | 25                      |
| globalSettings__mail__smtp__ssl      | true                     |
| globalSettings__mail__smtp__username | bitwarden@yourdomain.com |
| globalSettings__mail__smtp__password | YOUR_PASSWORD_HERE       |

To test the email function without running any scripts, log into your BitWarden Server and open an elevated PowerShell instance:

```
sudo pwsh
```

Make your way to the BitWarden Application Directory:

```
cd /opt/bitwarden
```

Copy/Paste the following code to test the Email Function (Replace `YOUR_EMAIL_HERE` within $EmailAddresses with your own Email:

```
$EmailAddresses = @("YOUR_EMAIL_HERE")

$GLOBAL_ENV = '/opt/bitwarden/bwdata/env/global.override.env'
$EMAIL_PARAMS = @{}
$EMAIL_SETTINGS = @{}

Import-Module ./ZHLBitWarden.psm1

$EMAIL_SETTINGS = Get-ZHLBWEmailSettings -GlobalEnv $GLOBAL_ENV -ErrorAction Stop

$EMAIL_PARAMS.add('EmailAddresses', $EmailAddresses)
$EMAIL_PARAMS.add('FROM', $EMAIL_SETTINGS['From'])
$EMAIL_PARAMS.add('SMTPServer', $EMAIL_SETTINGS['SMTPServer'])
$EMAIL_PARAMS.add('SMTPPort', $EMAIL_SETTINGS['SMTPPort'])
$EMAIL_PARAMS.add('UseSSL', $EMAIL_SETTINGS['UseSSL'])
$EMAIL_PARAMS.add('Creds', $EMAIL_SETTINGS['Creds'])

$EMAIL_SETTINGS

Send-ZHLBWEmail @EMAIL_PARAMS -Subject "Test Email" -Body "This is a test email."
```

Example:

![image](https://user-images.githubusercontent.com/107972707/229326644-9ea4e193-5e6a-4fc5-90a5-13a6897be036.png)

If it doesn't work, let me know!

**Comment by tcmp98724** [comment]
Hello! So that test did work, however, I am using port 587. It worked fine with that, and I got the test email, but it's still not working otherwise. The way I am testing it is like this, along with the result of it...

<img width="1821" alt="image" src="https://user-images.githubusercontent.com/52106734/229369617-def3beae-cd3a-4a96-9526-391ac9da29fb.png">

*sorry, to be a little clearer, port 587 works fine for me for the test email, as well as BitWarden sending emails like it should, but the scripts do not send email. It does not work at all with anything on port 25, so this leads me to believe port 587 is correct.

**Comment by ZacksHomeLab** [comment]
After looking into it, there is a logic issue within `backup-bitwarden.ps1`. The script isn't retrieving the provided credentials in `'/opt/bitwarden/bwdata/env/global.override.env'`.

If the script cannot retrieve the credentials, it'll fallback on an insecure channel. 

I'll fix that here in a bit!

**Comment by ZacksHomeLab** [comment]
The issue has been resolved. To retrieve the new scripts, you can run the following commands on your BitWarden Server:
```
rm /opt/bitwarden/backup-bitwarden.ps1 && wget https://raw.githubusercontent.com/ZacksHomeLab/BitWarden-Scripts/main/scripts/backup-bitwarden.ps1
```
```
rm /opt/bitwarden/update-bitwarden.ps1 && wget https://raw.githubusercontent.com/ZacksHomeLab/BitWarden-Scripts/main/scripts/update-bitwarden.ps1
```
```
rm /opt/bitwarden/update-bitwardenSSL.ps1 && wget https://raw.githubusercontent.com/ZacksHomeLab/BitWarden-Scripts/main/scripts/update-bitwardenSSL.ps1
```

Let me know if it's fixed on your end!

**Comment by tcmp98724** [comment]
Hello again! Looks like your updated script works! It also went through and removed the backups that were older than 14 days old. Didn't even think to check to see if it did that before but looks like that was affected too and its now fixed. One thing to note, and it may just be me and my install, but the 3 commands you listed did remove the old file, but when it put the new files in the contents were not your scripts, it looks like a transcript of the wget command or something like that. Wasn't a big deal, I just copied and pasted from your scripts folder in GitHub into nano on the dockerhost. Thanks again for the awesome work on this and taking time out of your day to work with me on this! Very much appreciated!
